import type { Garment } from "@/types/youcam";

/**
 * Curated demo catalog. Images are simple flat-color garment-silhouette
 * PNGs (see public/garments/), rasterized locally from hand-built SVGs to
 * avoid any third-party/licensing issues in a hackathon submission.
 * Confirmed against a live account: a rasterized silhouette like this is
 * enough for the Apparel VTO ("cloth") task to produce a real, convincing
 * on-model render (a flat solid-color swatch is not — it fails with
 * "Output too similar to source"). Real product photography will still
 * look better — swap `imageUrl` before a final demo if time allows.
 */
export const GARMENTS: Garment[] = [
  {
    id: "sunset-silk-blouse",
    name: "Sunset Silk Blouse",
    category: "top",
    colorFamily: "earth",
    hexSwatch: "#D97C4A",
    undertoneFit: ["warm", "neutral"],
    occasion: ["work", "date-night"],
    imageUrl: "/garments/sunset-silk-blouse.png",
    description: "A warm terracotta silk blouse with a soft draped neckline.",
  },
  {
    id: "sapphire-wrap-dress",
    name: "Sapphire Wrap Dress",
    category: "dress",
    colorFamily: "jewel",
    hexSwatch: "#2A4D8F",
    undertoneFit: ["cool", "neutral"],
    occasion: ["event", "date-night"],
    imageUrl: "/garments/sapphire-wrap-dress.png",
    description: "A deep sapphire wrap dress with a flattering waist tie.",
  },
  {
    id: "ivory-tailored-blazer",
    name: "Ivory Tailored Blazer",
    category: "outerwear",
    colorFamily: "neutral",
    hexSwatch: "#EDE6DA",
    undertoneFit: ["warm", "cool", "neutral"],
    occasion: ["work", "event"],
    imageUrl: "/garments/ivory-tailored-blazer.png",
    description: "A crisp ivory blazer that layers over almost anything.",
  },
  {
    id: "emerald-midi-dress",
    name: "Emerald Midi Dress",
    category: "dress",
    colorFamily: "jewel",
    hexSwatch: "#1F6E52",
    undertoneFit: ["cool", "neutral"],
    occasion: ["event", "work"],
    imageUrl: "/garments/emerald-midi-dress.png",
    description: "A structured emerald midi dress with a tailored fit.",
  },
  {
    id: "terracotta-knit-top",
    name: "Terracotta Knit Top",
    category: "top",
    colorFamily: "earth",
    hexSwatch: "#C1613B",
    undertoneFit: ["warm"],
    occasion: ["casual", "work"],
    imageUrl: "/garments/terracotta-knit-top.png",
    description: "A relaxed terracotta knit top in a soft ribbed fabric.",
  },
  {
    id: "blush-satin-top",
    name: "Blush Satin Top",
    category: "top",
    colorFamily: "pastel",
    hexSwatch: "#F1C6C0",
    undertoneFit: ["cool", "neutral"],
    occasion: ["date-night", "event"],
    imageUrl: "/garments/blush-satin-top.png",
    description: "A soft blush satin top with a subtle sheen.",
  },
  {
    id: "charcoal-wool-coat",
    name: "Charcoal Wool Coat",
    category: "outerwear",
    colorFamily: "neutral",
    hexSwatch: "#3B3A3E",
    undertoneFit: ["warm", "cool", "neutral"],
    occasion: ["work", "casual"],
    imageUrl: "/garments/charcoal-wool-coat.png",
    description: "A structured charcoal wool coat for cooler days.",
  },
  {
    id: "marigold-sundress",
    name: "Marigold Sundress",
    category: "dress",
    colorFamily: "bold",
    hexSwatch: "#E8A93B",
    undertoneFit: ["warm"],
    occasion: ["casual", "date-night"],
    imageUrl: "/garments/marigold-sundress.png",
    description: "A bright marigold sundress with a flowy silhouette.",
  },
  {
    id: "lavender-cardigan",
    name: "Lavender Cardigan",
    category: "outerwear",
    colorFamily: "pastel",
    hexSwatch: "#C9B6DE",
    undertoneFit: ["cool", "neutral"],
    occasion: ["casual", "work"],
    imageUrl: "/garments/lavender-cardigan.png",
    description: "A soft lavender cardigan, easy to layer over any top.",
  },
  {
    id: "ruby-cocktail-dress",
    name: "Ruby Cocktail Dress",
    category: "dress",
    colorFamily: "bold",
    hexSwatch: "#A11F3A",
    undertoneFit: ["warm", "neutral"],
    occasion: ["event", "date-night"],
    imageUrl: "/garments/ruby-cocktail-dress.png",
    description: "A striking ruby cocktail dress with a fitted bodice.",
  },
  {
    id: "olive-utility-jacket",
    name: "Olive Utility Jacket",
    category: "outerwear",
    colorFamily: "earth",
    hexSwatch: "#5B5F3D",
    undertoneFit: ["warm", "neutral"],
    occasion: ["casual"],
    imageUrl: "/garments/olive-utility-jacket.png",
    description: "A relaxed olive utility jacket with patch pockets.",
  },
  {
    id: "cobalt-button-up",
    name: "Cobalt Button-Up",
    category: "top",
    colorFamily: "jewel",
    hexSwatch: "#1E4E8C",
    undertoneFit: ["cool"],
    occasion: ["work", "casual"],
    imageUrl: "/garments/cobalt-button-up.png",
    description: "A crisp cobalt button-up with a clean, modern collar.",
  },
  {
    id: "cream-linen-top",
    name: "Cream Linen Top",
    category: "top",
    colorFamily: "neutral",
    hexSwatch: "#F2E9D8",
    undertoneFit: ["warm", "cool", "neutral"],
    occasion: ["casual", "work", "date-night"],
    imageUrl: "/garments/cream-linen-top.png",
    description: "An easy cream linen top that flatters almost every tone.",
  },
];
